# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates Python Static Analyzer (Pysa) with
# GitHub's Code Scanning feature.
#
# Python Static Analyzer (Pysa) is a security-focused static
# analysis tool that tracks flows of data from where they
# originate to where they terminate in a dangerous location.
#
# See https://pyre-check.org/docs/pysa-basics/

name: Pysa

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '35 18 * * 0'

permissions:
    contents: read

jobs:
  pysa:
    permissions:
      actions: read
      contents: read
      security-events: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.10'

      - name: Install Pysa
        run: pip install pyre-check
        shell: bash

      - name: Install dependencies
        run: pip install -r requirements.txt
        shell: bash

      - name: Prepare SAPP filters directory
        run: |
          filters_path='tmp/sapp_filters'
          mkdir -p $filters_path
          echo 'Copying default sapp filters to temporary directory'
          cp -r ${{env.LD_LIBRARY_PATH}}/pyre_check/pysa_filters/* $filters_path
        shell: bash

      - name: Set up Pyre
        run: echo -e '\n' | pyre init
        shell: bash

      - name: Run Pyre Infer
        run: |
          pyre infer
          pyre infer -i --annotate-from-existing-stubs
        shell: bash
        
      - name: Run Pysa
        run: pyre analyze --no-verify --save-results-to=./pysa-output
        shell: bash

      - name: Saving Pysa results for SAPP
        uses: actions/upload-artifact@v3
        with:
          name: pysa-results
          path: pysa-output
          if-no-files-found: error

      - name: Postprocess Pysa results with SAPP
        uses: facebook/sapp-action@main
        with:
          version: latest
          artifact-handle: pysa-results
          filters-directory: tmp/sapp_filters
